name: data_literacy_project
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - matplotlib
  - jupyter
  - scipy
  - requests
  - openpyxl
  - seaborn
  - plotly # for interactive plots
  - statsmodels
  - patsy.highlevel
  - datetime
  - pickle
  - pip:
    - openmeteo-requests
    - requests-cache